#!/bin/bash

wget -q http://developer.download.nvidia.com/compute/cuda/11.0.1/local_installers/cuda_11.0.1_450.36.06_linux.run
chmod +x cuda_11.0.1_450.36.06_linux.run
./cuda_11.0.1_450.36.06_linux.run --override --toolkit --silent
rm -f cuda_11.0.1_450.36.06_linux.run

cat <<EOF > /etc/profile.d/cuda.sh
export CUDA_PATH=/usr/local/cuda
export PATH=\$PATH:/usr/local/cuda/bin
EOF