#!/bin/bash

set -ex

pacman -R --noconfirm zasdfgbnmsystem-desktop
pacman -Rns --noconfirm cuda cudnn magma
sudo -u user yaourt -Sy --noconfirm gcc8

wget -q http://developer.download.nvidia.com/compute/cuda/11.0.1/local_installers/cuda_11.0.1_450.36.06_linux.run
chmod +x cuda_11.0.1_450.36.06_linux.run
bash --verbose ./cuda_11.0.1_450.36.06_linux.run --override --toolkit --silent
rm -f cuda_11.0.1_450.36.06_linux.run

# install CUDA 11.0 CuDNN
# cuDNN license: https://developer.nvidia.com/cudnn/license_agreement
mkdir tmp_cudnn && cd tmp_cudnn
wget -q http://developer.download.nvidia.com/compute/redist/cudnn/v8.0.0/cudnn-11.0-linux-x64-v8.0.0.180.tgz -O cudnn-8.0.tgz
tar xf cudnn-8.0.tgz
cp -a cuda/include/* /usr/local/cuda/include/
cp -a cuda/lib64/* /usr/local/cuda/lib64/
cd ..
rm -rf tmp_cudnn
ldconfig

cat <<EOF > /etc/profile.d/cuda.sh
export CUDA_PATH=/usr/local/cuda
export PATH=\$PATH:/usr/local/cuda/bin
EOF